### ISSUE TITLE
Automatic path on select kind is incorrect

### ISSUE THREAD

**Issue by cgourdin** [occiware/OCCInterface#10]
Hello,
I've searched in OCCI documentation (1.1 and 1.2) and i didn't found that "categories" word should be in path to render category collection. In fact, in MART server i use directly : /network/ not /categories/network/ . I think it's from Erocci implementation but this is not for a general purpose.

Here my network kind selected :
<img width="651" alt="capture d ecran 2016-11-28 a 13 52 14" src="https://cloud.githubusercontent.com/assets/17008842/20668991/ebbd3fb2-b571-11e6-9a73-4ec754a7a04c.png">
This give me /categories/network , this is bad.
This should give me : /network/ , this way is better to understand but is no more compatible with Erocci.

Thank you.

**Comment by mdutoo** [comment]
Solved in 16cd832
