### ISSUE TITLE
Model part (blue button) doesn't work

### ISSUE THREAD

**Issue by cgourdin** [occiware/OCCInterface#11]
Hello, when i target on a ressource path like : /vms/a1cf3896-500e-48d8-a3f5-a8b3601bcdd8
 and i click on "M" button (in blue color), it give me this message :
"Impossible to go to the model of this resource "
this look likes : 
<img width="847" alt="capture d ecran 2016-11-28 a 14 43 57" src="https://cloud.githubusercontent.com/assets/17008842/20670429/29d37e36-b579-11e6-8632-0ff5568fb5f8.png">
I click on blue button : 
<img width="845" alt="capture d ecran 2016-11-28 a 14 45 05" src="https://cloud.githubusercontent.com/assets/17008842/20670468/4b86bade-b579-11e6-84dc-47265a37390b.png">

So i have a question, what is a model for you, is this the interface for the current kind ? Like /compute/-/ :
<img width="856" alt="capture d ecran 2016-11-28 a 14 47 06" src="https://cloud.githubusercontent.com/assets/17008842/20670545/987fd302-b579-11e6-982d-ec27e6ad770b.png">

**Comment by Romathonat** [comment]
I developped OCCInterface with Erocci as a backend server (the only one that worked correctly at the time), and with erocci you access to a resource with its id with:
```
/acf1d5454-sdd etc...
```
I don't know if this is important but it is what I had in mind.
Moreover, if I look a the code [here](https://github.com/occiware/OCCInterface/blob/master/src/components/buttons/ModelButton.js#L21) I see that the model button retrieve the model thanks to the .kind of an object. Actually, it seems that in you example, you don't have a single object but a list, so the OCCInterface don't know how to access to the kind attribute.

**Comment by cgourdin** [comment]
Effectively when one entity is rendered as output, it must be rendered as single not a collection.
Thank you to see that, i will correct this.
So the process i had is correct :
- get entity
- click on blue button
After this should give the kind model of this entity ?

**Comment by Romathonat** [comment]
Yes that is what the model button should do.

**Comment by cgourdin** [comment]
That works !!! Thank you :-). I can close this !
