### ISSUE TITLE
The plural of data is data, not "datas"

### ISSUE THREAD

**Issue by gibello** [occiware/OCCInterface#16]
Datas (sic) are everywhere: in the text (like in "You are going to create and/or delete datas" ...) but also in the JSON of the queries (eg. in a POST request: { "text": "stop it", "post": [ { "address": "/compute/6df690d2-3158-40c4-88fb-d1c41584d6e5?action=stop", "datas": { "action":"http://schemas.ogf.org/occi/infrastructure/compute/action#stop", "attributes": { "method": "graceful" } } } ] }).
No standard protocol can embed typos...

**Comment by mdutoo** [comment]
Solved, should also be backward compatible (but please update your own samples if you have any :).
