### ISSUE TITLE
node (& heroku) deployment : support more than one proxied OCCI server simultaneously

### ISSUE THREAD

**Issue by mdutoo** [occiware/OCCInterface#2]
by managing a map of server proxies keyed by their URL (rather than a single proxy), saving in user session which one the user currently uses, and (in a perfect world) nicely deleting a proxy on session removal (timeout...) if nobody else still uses it.

(because for now, when one user changes the proxied OCCI server on ex. the heroku deployment, it changes for all other users)

**Comment by Romathonat** [comment]
Done. However it is not perfect because the storage mechanism for session is the default, which could leads to some memory leaks on the server. A redis storage would be better, unfortunately I am not sure that we can put one on Heroku, so for now it is ok to keep it that way.
