### ISSUE TITLE
[QA] reduce dependencies when frontend only mode

### ISSUE THREAD

**Issue by jeanparpaillon** [occiware/OCCInterface#4]
When built as erocci frontend, OCCInterface pulls a lot of unneeded dependancies (server side, I suppose).

frontend mode should get rid of server side deps (and maybe some others).

Reducing deps implies:
- better maintainability
- better security

From a fresh install and build:

```
$ du -hs node_modules/
150M    node_modules/
```

```
$ ls node_modules/ | wc -l
764
```

-> problems of maintainability / security...

Unacceptable weight for a simple frontend:

```
$ du -hs dist/
2,8M    dist/
```

**Comment by Romathonat** [comment]
Well, it does not really depends on me, node project are often super heavy with node_modules (dependencies require other dependencies...). OCCinterface needs some dependencies because it is not a "simple" frontend (like an HTML page...), but a complete app ! I'll check what I can do but I am not sure I can do way better :/

**Comment by jeanparpaillon** [comment]
At least, you can remove server-side deps (maybe in a specific frontend-only mode ?)
And maybe the problem comes from the build tool ? gulp, grunt or other instead of npm ?

I'm working on similar in technology (react.js, webpack, etc), but much more consequent in term of pages and components, projects where size is at max 1/3rd from this

Concrete issues are:
- maintainability: too much deps
- security
- download size for user (let say dev is less important): 2.8MB

**Comment by Romathonat** [comment]
For the user the download size is not 2.8MB, it is ~280kB (look at firebug) for bundle.js.
With --production flag on npm install, we can go down to 116MB. Removing server side (express) : 114 MB. (nearly nothing to gain seeing the work needed to change the project). We'll look at it later, but I am quite pessimistic.

**Comment by Romathonat** [comment]
I managed to reduce to ~77MB.
Next improvement could let us go down to 55M.

**Comment by jeanparpaillon** [comment]
:+1: You can do it ;)

**Comment by Romathonat** [comment]
``` bash
du -hs deps/erocci_frontend/node_modules/
53M deps/erocci_frontend/node_modules/
```

Does it seems acceptable? If yes, you can close :)

**Comment by jeanparpaillon** [comment]
Nice :)
